app/models/seat.py
from datetime import datetime

from sqlalchemy.orm import relationship, backref

from app.extensions import db
from sqlalchemy import Column, Integer, ForeignKey, DateTime, String


class Seat(db.Model):
    __tablename__ = 'seat'
    id = Column(Integer(), primary_key=True)
    x_axis = Column(String(255), nullable=False)
    y_axis = Column(String(255), nullable=False)
    status = Column(String(255), nullable=False, default='available')
    event_id = Column(Integer(), ForeignKey('event.id'), nullable=False)
    created_at = Column(DateTime(), default=datetime.utcnow)
    updated_at = Column(DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)
    event = relationship('Event', backref=backref('seats', lazy='joined'))

app/routes/seat/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, HiddenField, IntegerField
from wtforms.fields.datetime import DateTimeLocalField
from wtforms.validators import DataRequired, Length
from flask_babel import lazy_gettext, gettext


class SeatNotAvailableForm(FlaskForm):
    submit = SubmitField(lazy_gettext('Make not available'))


class SeatAvailableForm(FlaskForm):
    submit = SubmitField(lazy_gettext('Make available'))

app/routes/seat/__init__.py
from flask import Blueprint

bp = Blueprint('seat', __name__)

from app.routes.seat import routes

app/routes/seat/routes.py
from app.extensions import db
from app.routes.seat import bp
from flask import redirect, url_for, flash
from flask_security import roles_required
from flask_babel import gettext

from app.models.seat import Seat


@bp.route('/<int:seat_id>/change_status', methods=['POST'])
@roles_required('Admin')
def change_status(seat_id):
    seat = Seat.query.get(seat_id)
    if seat.status == 'not_available':
        seat.status = 'available'
    elif seat.status == 'available':
        seat.status = 'not_available'
    else:
        flash(gettext('Seat status is invalid'), 'error')
        return redirect(url_for('event.seats', event_id=seat.event_id))

    db.session.commit()
    flash(gettext('Seat status updated'), 'success')

    return redirect(url_for('event.seats', event_id=seat.event_id))

app/templates/components/seat/_render_public_seats.html
{% from 'components/form/_macros.html' import render_form %}

{% macro render_icon(status) %}
    {% if status == 'available' %}
        <i class="fa-regular fa-circle text-yellow-300"></i>
    {% elif status == 'not_available' %}
        <i class="fa-regular fa-circle-xmark text-gray-400"></i>
    {% elif status == 'occupied' %}
        <i class="fa-solid fa-circle-user text-green-400"></i>
    {% elif status == 'my_position' %}
        <i class="fa-solid fa-circle-user text-red-600 "></i>
    {% endif %}
{% endmacro %}

{% macro render_seats(seats, reserve_seat_form, remove_reservation_form, current_user) %}
    <div class="">
        <h1 class="text font-bold text-white text-center bg-amber-950 rounded mb-2 p-1 w-full">
            {{ _('Stage') }}
        </h1>
        <table class="w-full p-2">
            <thead>
            <tr>
                <th></th>
                {% set ns = namespace(unique_x_axis=[]) %}
                {% for seat in seats %}
                    {% if seat.x_axis not in ns.unique_x_axis %}
                        <th>{{ seat.x_axis }}</th>
                        {% set _ = ns.unique_x_axis.append(seat.x_axis) %}
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% set ns = namespace(last_row=None) %}
            {% for seat in seats %}
                {% if loop.first or ns.last_row != seat.y_axis %}
                    {% if not loop.first %}
                        </tr>
                    {% endif %}
                    <tr>
                    <td>{{ seat.y_axis }}</td>
                {% endif %}
            <td>
                <div class="p-1">

                    {{ render_modal(seat, reserve_seat_form, remove_reservation_form, current_user) }}

                </div>
            </td>

            {% if loop.last %}
                </tr>
            {% endif %}
                {% set ns.last_row = seat.y_axis %}
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endmacro %}

{% macro render_modal(seat, reserve_seat_form, remove_reservation_form, current_user) %}
    <div x-data="{ open: false }">
        <!-- Button to open the modal -->
        <button @click="open = true" class="">
            {{ render_icon(seat.status) }}
        </button>

        <!-- Modal -->
        <div x-show="open" x-cloak>
            <div class="fixed inset-0 bg-gray-800 opacity-60"></div>
            <div class="fixed top-12 left-0 w-full flex justify-center">
                <div class="relative w-full flex justify-between p-1 m-6 md:max-w-md md:m-0">
                    <div class="w-full h-full text-center bg-white rounded-lg">
                        <h4 class="text-2xl font-bold p-2">
                            {{ _('Seat') }}: {{ seat.x_axis }}{{ seat.y_axis }}
                        </h4>
                        {% if seat.status == 'available' %}
                            {% if current_user.is_authenticated %}
                                {{ render_form(reserve_seat_form, action=url_for('home.reserve', seat_id=seat.id)) }}
                            {% else %}
                                <p class="text-center text-red-500 mb-6">{{ _('You must login to reserve seat.') }}</p>
                            {% endif %}
                        {% elif seat.status == 'not_available' %}
                            <div class="w-full text-red-700 px-4 py-3">
                                <p class="font-bold py-2">{{ _('Not available') }}</p>
                            </div>
                        {% elif current_user.is_authenticated and current_user.id == seat.reservation.user_id %}
                            <div class="px-4 py-3">
                                <p class="font-bold py-2">{{ _('Reserved by') }}</p>
                                <p class="text-sm">{{ _('Partner 1: ') }} {{ seat.reservation.partner_1 }}</p>
                                <p class="text-sm">{{ _('Partner 2: ') }} {{ seat.reservation.partner_2 }}</p>
                                {{ render_form(remove_reservation_form, action=url_for('home.remove_reservation', seat_id=seat.id)) }}
                            </div>
                        {% else %}
                            <div class="w-full text-blue-700 px-4 py-3">
                                <p class="font-bold py-2">{{ _('Reserved by') }}</p>
                                <p class="text-sm">{{ _('Partner 1: ') }} {{ seat.reservation.partner_1 }}</p>
                                <p class="text-sm">{{ _('Partner 2: ') }} {{ seat.reservation.partner_2 }}</p>
                            </div>
                        {% endif %}
                    </div>

                    <button type="button" x-on:click="open=false"
                            class="absolute -top-2 -right-2 bg-white rounded-full px-1">
                        <i class="fa-regular fa-circle-xmark"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

{% endmacro %}

app/templates/components/seat/_render_seats.html
{% import 'components/form/_macros.html' as render_form %}

{% macro render_icon(status) %}
    {% if status == 'available' %}
        <i class="fa-regular fa-star text-yellow-300"></i>
    {% elif status == 'not_available' %}
        <i class="fa-regular fa-circle-xmark text-gray-400"></i>
    {% elif status == 'occupied' %}
        <i class="fa-solid fa-star text-green-400"></i>
    {% elif status == 'my_position' %}
        <i class="fa-solid fa-star text-red-600 "></i>
    {% endif %}
{% endmacro %}

{% macro render_seats(seats, seat_make_not_available_form) %}
    <div class="">
        <h1 class="text font-bold text-white text-center bg-amber-950 rounded mb-2 p-1 w-full">
            {{ _('Stage') }}
        </h1>
        <table class="w-full p-2">
            <thead>
            <tr>
                <th></th>
                {% set ns = namespace(unique_x_axis=[]) %}
                {% for seat in seats %}
                    {% if seat.x_axis not in ns.unique_x_axis %}
                        <th>{{ seat.x_axis }}</th>
                        {% set _ = ns.unique_x_axis.append(seat.x_axis) %}
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% set ns = namespace(last_row=None) %}
            {% for seat in seats %}
                {% if loop.first or ns.last_row != seat.y_axis %}
                    {% if not loop.first %}
                        </tr>
                    {% endif %}
                    <tr>
                    <td>{{ seat.y_axis }}</td>
                {% endif %}
            <td>
                <div class="p-1">
                    <form method="POST" action="{{ url_for('seat.change_status', seat_id=seat.id) }}">
                        <button type="submit">
                            {{ render_icon(seat.status) }}
                        </button>
                    </form>
                </div>
            </td>

            {% if loop.last %}
                </tr>
            {% endif %}
                {% set ns.last_row = seat.y_axis %}
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endmacro %}

app/templates/components/seat/_reservattion_confirmation.html
{% macro reservation_confirmation(seat, reservation) %}

{% endmacro %}